// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_if_wsPuZW0z3gpYwhQ2XCAN3LBNMdCM',
    appId: '1:199524755177:web:9da667ff82b177a9837278',
    messagingSenderId: '199524755177',
    projectId: 'zimproshop-49917',
    authDomain: 'zimproshop-49917.firebaseapp.com',
    storageBucket: 'zimproshop-49917.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGmkinX5AWOgyLqxboGDz4eWCyZJT24bE',
    appId: '1:199524755177:android:2f76abfb60d4271e837278',
    messagingSenderId: '199524755177',
    projectId: 'zimproshop-49917',
    storageBucket: 'zimproshop-49917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjV_JSSVRoBJFgzKNeFN3bPNfBHLesFhg',
    appId: '1:199524755177:ios:2bea1ff124e551c3837278',
    messagingSenderId: '199524755177',
    projectId: 'zimproshop-49917',
    storageBucket: 'zimproshop-49917.appspot.com',
    iosClientId: '199524755177-9kfac63aqh7hamiuaonako11dodqt9ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineShop',
  );
}
